title: Minjin Chae
description: PhD Candidate in Sociology at Harvard University studying work, family, gender, and inequality.
url: https://chaeminjin.github.io
markdown: kramdown
exclude:
  - Readme.md
